services:
  # Database for Auth/Identities
  identities-db:
    image: postgres:15-alpine
    container_name: phonenexus-identities-db
    environment:
      POSTGRES_DB: ${IDENTITIES_DB_NAME:-identities_db}
      POSTGRES_USER: ${IDENTITIES_DB_USER:-user}
      POSTGRES_PASSWORD: ${IDENTITIES_DB_PASSWORD:-password}
    ports:
      - "5431:5432"

  # Database for Products
  products-db:
    image: postgres:15-alpine
    container_name: phonenexus-products-db
    environment:
      POSTGRES_DB: ${PRODUCTS_DB_NAME:-products_db}
      POSTGRES_USER: ${PRODUCTS_DB_USER:-user}
      POSTGRES_PASSWORD: ${PRODUCTS_DB_PASSWORD:-password}
    ports:
      - "5432:5432"

  # Database for Sales/Orders
  sales-db:
    image: postgres:15-alpine
    container_name: phonenexus-sales-db
    environment:
      POSTGRES_DB: ${SALES_DB_NAME:-sales_db}
      POSTGRES_USER: ${SALES_DB_USER:-user}
      POSTGRES_PASSWORD: ${SALES_DB_PASSWORD:-password}
    ports:
      - "5433:5432"

  # Adminer for DB management
  adminer:
    image: adminer
    container_name: phonenexus-adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: phonenexus-redis
    ports:
      - "6379:6379"
