spring:
  application:
    name: identities-service
  datasource:
    url: jdk.jdbc.postgresql://localhost:5431/identities_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false # For now, until discovery is up

# Security JWT configuration
phonenexus:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000 # 1 day
