spring:
  application:
    name: identities-service
  datasource:
    url: jdbc:postgresql://localhost:5431/${IDENTITIES_DB_NAME:identities_db}
    username: ${IDENTITIES_DB_USER:user}
    password: ${IDENTITIES_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false # For now, until discovery is up

# Security JWT configuration
phonenexus:
  app:
    jwtSecret: ${JWT_SECRET:phoneNexusSecretKeyForSecurityPurposesOnlyDoNotUseInProductionWithoutChangingIt}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:3600000}
    jwtRefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:86400000}
